# See https://docs.giantswarm.io/reference/platform-api/chart-metadata/
# for details and background.

apiVersion: v2
appVersion: 0.1.0
name: openssf-scorecard-exporter
description: OpenSSF Scorecard Exporter scrapes the OpenSSF API and exposes Prometheus metrics for Scorecard data.
home: https://github.com/giantswarm/openssf-scorecard-exporter
icon: https://s.giantswarm.io/app-icons/openssf/2/light.png
version: 0.1.0
annotations:
  # Adapt to 'giantswarm' if this application is not to be deployed by customers
  io.giantswarm.application.audience: all
  # Adapt to 'true' if Giant Swarm takes responsibility for this app where it's deplyed
  io.giantswarm.application.managed: "false"
  # used through .Chart.Annotations . Please replace TEAM-NAME with your team's short name, e. g. 'shield'  for team-shield
  io.giantswarm.application.team: "shield"
