# See https://docs.giantswarm.io/reference/platform-api/chart-metadata/
# for details and background.

apiVersion: v2
appVersion: 0.1.0
name: openssf-scorecard-exporter
description: OpenSSF Scorecard Exporter scrapes the OpenSSF API and exposes Prometheus metrics for Scorecard data.
home: https://github.com/giantswarm/openssf-scorecard-exporter
icon: https://s.giantswarm.io/app-icons/openssf/2/light.png
version: 0.1.0
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "false"
  io.giantswarm.application.team: "shield"
